openapi: 3.0.0
info:
  title: Laptop Lens API
  description: "API to serve the stocks data"
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /login:
    post: 
      tags:
        - "Authentication & Authorization"
      summary: "Login user"
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "User login"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
        '401': 
          description: "Failed to login"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /signup:
    post:
      tags:
        - "Authentication & Authorization"
      summary: "Register new account"
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: "Success register new account"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string
                  message:
                    type: string
        '400':
          description: "Failed register new account"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string
                  message:
                    type: string
  /logout:
    post: 
      tags:
        - "Authentication & Authorization"
      summary: "Logout account"
      responses:
        '200':
          description: "Success to logout"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /stocks:
    get:
      security:
        - firebaseAuth: []
      tags:
        - "Stocks API"
      summary: "Return all stocks data"
      parameters:
        - in: query
          name: name
          schema: 
            type: string
          description: "Find stock by name"
      responses:
        '200':
          description: "List of stocks"
          content: 
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  data: 
                    type: array
                    items:
                      $ref: "#/components/schemas/stocks"
        '404':
          description: "Data not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /stocks/{id}:
    get:
      security:
          - firebaseAuth: []
      tags:
        - "Stocks API"
      summary: "Return stock data by ID"
      parameters:
        - in: path
          name: "id"
          description: "Stocks ID"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Single stock data"
          content: 
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  data:
                    type: object
                    $ref: '#/components/schemas/stocks'
        '404':
          description: "Data not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /stocks/incoming:
    post:
      security:
        - firebaseAuth: []
      tags:
        - "Stocks API"
      summary: "Insert incoming transaction data"
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              $ref: "#/components/schemas/incoming_stocks"
      responses:
        '201':
          description: "Success insert data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                      price: 
                        type: number
                      date:
                        type: string
                      quantity:
                        type: number
        '400':
          description: "Failed to insert data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /stocks/outgoing:
    post:      
      tags:
        - "Stocks API"
      security:
        - firebaseAuth: []
      summary: "Insert outgoing transaction data"
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                date:
                  type: string
                quantity:
                  type: number
      responses:
        '201':
          description: "Success insert data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                      price:
                        type: number
                      date:
                        type: string
                      sales:
                        type: number
        '400':
          description: "Failed to insert data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /predict:
    post: 
      tags:
        - "Stocks API"
      security:
        - firebaseAuth: []
      summary: "Predict sales"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
                  description: The CSV file to upload
      responses:
        '200':
          description: "Success predict data"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
  /stocks/export:
    post:      
      tags:
        - "Stocks API"
      security:
        - firebaseAuth: []
      summary: "Export data to csv"
      parameters:
        - in: query
          name: month
          schema: 
            type: number
          description: "Filter by month"
      responses:
        '201':
          description: "Success export data"
          content:
            application/csv:
              schema:
                type: string
                format: binary


components:
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
  schemas:
    stocks:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        price:
          type: number
        total_stocks:
          type: number
    incoming_stocks:
      type: object
      properties:
        name:
          type: string
        vendor_name:
          type: string
        price: 
          type: number
        date:
          type: string
        quantity:
          type: number